# Generated by Django 2.2.4 on 2019-09-02 16:04

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('province_abbr', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('street', models.TextField(max_length=50)),
                ('city', models.TextField(max_length=50)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='jobsite.Province')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('title', models.CharField(max_length=50)),
                ('address_one', models.CharField(max_length=120)),
                ('address_two', models.CharField(max_length=120)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='jobsite.Province')),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_firstname', models.CharField(max_length=30)),
                ('user_lastname', models.CharField(max_length=30)),
                ('user_email', models.EmailField(max_length=254)),
                ('user_city', models.CharField(max_length=50)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('cover_letter', models.TextField(blank=True)),
                ('cover_letter_attachment', models.FileField(blank=True, upload_to='documents/cover_letters/')),
                ('resume', models.TextField(blank=True)),
                ('resume_attachment', models.FileField(blank=True, upload_to='documents/resumes/')),
                ('job', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='jobsite.Job')),
                ('user_state', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='jobsite.Province')),
            ],
        ),
    ]
