# Generated by Django 2.2.4 on 2019-09-02 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobsite', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='job_application_url',
        ),
        migrations.RemoveField(
            model_name='job',
            name='project_id',
        ),
        migrations.RemoveField(
            model_name='job',
            name='requisition_id',
        ),
    ]
