# Generated by Django 2.2.4 on 2019-09-02 17:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('jobsite', '0002_data_migration_for_province'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='date_posted',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='job',
            name='address_two',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
