# Generated by Django 2.2.4 on 2019-09-02 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobsite', '0002_auto_20190902_0924'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='user',
        ),
        migrations.AddField(
            model_name='application',
            name='user_city',
            field=models.CharField(default='City', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='user_email',
            field=models.EmailField(default='user@email.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='user_firstname',
            field=models.CharField(default='firstname', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='user_lastname',
            field=models.CharField(default='lastname', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='user_state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='jobsite.Provence'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='application',
            name='cover_letter',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='cover_letter_attachment',
            field=models.FileField(blank=True, upload_to='documents/cover_letters/'),
        ),
        migrations.AlterField(
            model_name='application',
            name='resume',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='resume_attachment',
            field=models.FileField(blank=True, upload_to='documents/resumes/'),
        ),
        migrations.AlterField(
            model_name='job',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='jobsite.Provence'),
        ),
        migrations.AlterField(
            model_name='user',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='jobsite.Provence'),
            preserve_default=False,
        ),
    ]
