# Generated by Django 2.2.4 on 2019-09-03 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobsite', '0004_auto_20190902_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='resume_attachment',
            field=models.FileField(blank=True, upload_to='documents/resumes/%Y/%m/%d/'),
        ),
    ]
