# Generated by Django 2.2.4 on 2019-09-03 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobsite', '0005_auto_20190903_1016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='resume_attachment',
            field=models.FileField(blank=True, upload_to='documents/resumes/%Y/%m/%d/', verbose_name='Upload a Resume'),
        ),
        migrations.AlterField(
            model_name='application',
            name='user_city',
            field=models.CharField(max_length=50, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='application',
            name='user_email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='application',
            name='user_firstname',
            field=models.CharField(max_length=30, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='application',
            name='user_lastname',
            field=models.CharField(max_length=30, verbose_name='LastName'),
        ),
    ]
